### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by LDMBatman** [f4ble/Arkon#6] opened 2016-02-22 06:51 UTC
Hi, in some cases this is what happens : 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inn
er
    self.run()
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "E:\pyarc-master\ark\thread_handler.py", line 54, in worker
    thread_work_loop(item)
  File "E:\pyarc-master\ark\thread_handler.py", line 47, in thread_work_l
oop
    callback()
  File "E:\pyarc-master\ark\steam\steam_socket_core.py", line 139, in loo
p_communication
    if not cls.wait_for_response(send_packet):
  File "E:\pyarc-master\ark\steam\steam_socket_core.py", line 159, in wai
t_for_response
    packet, err = cls.socket_read(False)
  File "E:\pyarc-master\ark\steam\steam_socket.py", line 67, in socket_re
ad
    packet, err = super().socket_read(wait)
  File "E:\pyarc-master\ark\steam\steam_socket_core.py", line 226, in soc
ket_read
    packet = SteamPacket.unpack(data)
  File "E:\pyarc-master\ark\steam\steam_packet.py", line 47, in unpack
    obj._decode(binary_string)
  File "E:\pyarc-master\ark\steam\steam_packet_encoding.py", line 53, in
_decode
    body = binary_string[12:-2].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 16: ordinal
 not in range(128)

**Comment by f4ble** [comment] 2016-02-22 14:13
I've seen this as well. I haven't been able to solve it. Been focusing on the sql stability problems lately.

I have some ideas on how to solve it and it involves logging all data traffic so we can at least replicate the problem.

**Comment by LDMBatman** [comment] 2016-02-22 14:28
Wouldn't it be possible to solve it with a try: ... except: ? or with some function to relaunch pyark when this happens?

**Comment by f4ble** [comment] 2016-02-22 14:41
Yeah. I realized that as well. I've added exception handling in the latest commit. That means we can at least see the contents of the packet. So if you get this error post the contents here

**Comment by LDMBatman** [comment] 2016-02-22 15:42
Ok, i'll try this. Thank you

**Comment by LDMBatman** [comment] 2016-02-23 08:00
This is what i got :
01:43:46 [4] #  Keep Alive!
01:43:46 [4] #  Retrying waiting for response:
01:58:47 [4] #  ERROR : Unable to decode ascii for binary string:
b'\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Keep Alive\x00\x00/\x00\x00\x0
0\xca\x0c\x00\x00\x00\x00\x00\x00Server received, But no response!! \n \x00\x00'
[...]
  File "E:\pyarc-master\ark\steam\steam_packet_encoding.py", line 54, in
_decode
    body = binary_string[12:-2].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 16: ordinal
 not in range(128)

**Comment by f4ble** [comment] 2016-02-23 20:50
Multiple packets in one read() is the problem. There are two packets and only one is expected.

Interesting problem. I will fix! :)

Edit: Working on a new fix that will solve this and multipacket responses (single response bigger than 4096). Want to test this for a little while first before I commit as it's quite the big change.

**Comment by LDMBatman** [comment] 2016-02-24 09:31
If you are trying to explode the string i just show that \xca is not the only char that makes issues : 
r10:09:05 [0] #  ERROR : Unable to decode ascii for binary string:
b'\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Keep Alive\x00\x00!\x00\x00\x0
0\xeb\x00\x00\x00\x00\x00\x00\x00No Players Connected \n \x00\x00'

```
body = binary_string[12:-2].decode('ascii')
```

UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 16: ordinal
 not in range(128)

**Comment by LDMBatman** [comment] 2016-02-24 09:56
Once more with : 
b'\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Keep Alive\x00\x00!\x00\x00\x0
0\xe1\x00\x00\x00\x00\x00\x00\x00No Players Connected \n \x00\x00'

```
body = binary_string[12:-2].decode('ascii')
```

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 16: ordinal
 not in range(128)

**Comment by f4ble** [comment] 2016-02-24 16:24
The problem is that it's two packets. So when I'm trying to decode body it actually contains binary data from the second packet. This issue seems to be resolved in my upcoming commit. #needsTesting

**Comment by f4ble** [comment] 2016-02-24 16:46
Changes have been commited. Let me know if the problem persists.

**Comment by LDMBatman** [comment] 2016-02-24 17:05
Update done. Thank you for this huge fix. I'll tell you if problem persists (or not).

**Comment by LDMBatman** [comment] 2016-02-25 10:41
Seems ok. Good job !

**Comment by f4ble** [comment] 2016-02-25 13:32
Splendid! Thanks :)

**Closed as completed by f4ble** 2016-02-25 13:32 UTC
